linters-settings:
  govet:
    shadow: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gci:
    sections:
      - standard # Captures all standard packages if they do not match another section.
      - default # Contains all imports that could not be matched to another section type.
      - prefix(github.com/maxgio92/wgrep) # Groups all imports with the specified Prefix.
  tagliatelle:
    case:
      rules:
        json: snake

linters:
  enable-all: true
  disable:
    - godox
    - gochecknoglobals
    - gochecknoinits
    - exhaustruct
    - ireturn
    - lll
    - nonamedreturns
    - wrapcheck
    - varnamelen

issues:
  exclude-rules:
  - path: /
    linters:
    - typecheck

run:
  skip-dirs: []
